sudo: false

language: python

python:
   - 2.7
   - 3.3
   - 3.4
   - 3.5

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update -q conda
  - conda info -a

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
  - python setup.py install

script: python run_tests.py
